### ISSUE TITLE
Error in running iterative training

### ISSUE THREAD

**Issue by mahmoudEltaher** [isunchy/cuboid_abstraction#4]
Kindly i want to inquire about the following error :+1: 
when i try to run the command : 

python iterative_training.py --test_data test_tfrecords --test_iter number_of_shapes --ckpt /path/to/snapshots --cache_folder /path/to/save/test_results --test

Traceback (most recent call last):
  File "iterative_training.py", line 9, in <module>
    from data_loader import *
  File "util\data_loader.py", line 7, in <module>
    from cext import octree_database
  File "D:\Cottbus\code\cuboid_abstraction\cuboid_abstraction-master\cext\__init__.py", line 6, in <module>
    _primitive_gen_module = tf.load_op_library(os.path.join(_current_path, 'libprimitive_gen.so'))
  File "C:\Users\Mahmoud Eltaher\Anaconda3\envs\cuboid_abstraction\lib\site-packages\tensorflow\python\framework\load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: D:\Cottbus\code\cuboid_abstraction\cuboid_abstraction-master\cext\libprimitive_gen.so not found

**Comment by mahmoudEltaher** [comment]
@isunchy This is kindly reminder

**Comment by CA-TT-AC** [comment]
I think you did not compile cext successfully. Maybe you should complie as README firstly~
